---
- name: Uninstall VirtualBox Guest Additions from source (Unix)
  ansible.builtin.include_tasks: noauto_uninstall_source_Unix.yml
  when: ansible_os_family != 'Windows'

- name: Uninstall VirtualBox Guest Additions from source (Windows)
  ansible.builtin.include_tasks: noauto_uninstall_source_Windows.yml
  when: ansible_os_family == 'Windows'
