---
- name: Ensure virtualbox guest additions is installed via local
  block:
    - name: Remove existing installation
      ansible.builtin.include_tasks:
        file: noauto_remove_existing_installation.yml

    - name: Install OS-specific dependencies
      ansible.builtin.include_tasks: "{{ var_file }}"
      with_first_found:
        - "noauto_install_dep_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "noauto_install_dep_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "noauto_install_dep_{{ ansible_distribution }}.yml"
        - "noauto_install_dep_{{ ansible_os_family }}.yml"
        - "noauto_install_dep_{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: var_file

    - name: Check if the local file already exists
      ansible.builtin.stat:
        path: "{{ virtualbox_guest_download_path }}"
      register: virtualbox_guest_iso_file

    - name: Download guest additions
      when: not virtualbox_guest_iso_file.stat.exists
      ansible.builtin.get_url:
        url: "{{ virtualbox_guest_download_url }}"
        dest: "{{ virtualbox_guest_download_path }}"
        mode: "0644"

    - name: Mount local CD-ROM
      ansible.builtin.mount:
        path: "{{ virtualbox_guest_mount_path }}"
        src: "{{ virtualbox_guest_download_path }}"
        fstype: iso9660
        opts: ro,loop
        state: ephemeral
      become: true

    - name: Install new virtualbox Guest Additions version
      ansible.builtin.command:
        cmd: "{{ virtualbox_guest_installer_path }}"
      become: true
      changed_when: true
      register: virtualbox_guest_additions_install_result
      failed_when: virtualbox_guest_additions_install_result.rc not in [0, 2]
      notify: Reboot system

    - name: Unmount local CD-ROM
      ansible.builtin.mount:
        path: "{{ virtualbox_guest_mount_path }}"
        src: "{{ virtualbox_guest_local_mount_src }}"
        fstype: iso9660
        opts: ro,loop
        state: unmounted
      become: true

    - name: Remove virtualbox guest additions iso
      when: virtualbox_guest_download_iso_cleanup
      ansible.builtin.file:
        path: "{{ virtualbox_guest_download_path }}"
        state: absent
