---
- name: Check installed Virtualbox Guest Additions version (Unix)
  ansible.builtin.include_tasks: noauto_check_installed_version_Unix.yml
  when: ansible_os_family != 'Windows'

- name: Check installed Virtualbox Guest Additions version (Windows)
  ansible.builtin.include_tasks: noauto_check_installed_version_Windows.yml
  when: ansible_os_family == 'Windows'
