---
- name: Install VirtualBox Guest Additions from source (Unix)
  ansible.builtin.include_tasks: noauto_install_source_Unix.yml
  when: ansible_os_family != 'Windows'

- name: Install VirtualBox Guest Additions from source (Windows)
  ansible.builtin.include_tasks: noauto_install_source_Windows.yml
  when: ansible_os_family == 'Windows'
