---
- name: Ensure we are using pacman
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use pacman as a package manager."
  when: ansible_pkg_mgr != "pacman"

- name: Remove existing installation to ensure clean installation
  when: ansible_pkg_mgr == "pacman"
  block:
    - name: Remove existiing virtualbox guest utils
      community.general.pacman:
        name: "{{ virtualbox_guest_pkgs }}"
        state: absent
      become: true
