---
- name: Prepare
  hosts: all
  gather_facts: true

  vars_files:
    - ../../defaults/main.yml
    - ../../vars/molecule.yml

  tasks:
    - name: Import installed VirtualBox Guest Additions version check
      ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_version.yml"
      when: virtualbox_guest_installed_version is not defined

    - name: Uninstall current VirtualBox Guest Additions installation
      ansible.builtin.include_tasks: "../../tasks/noauto_uninstall.yml"
      when: virtualbox_guest_installed_version is defined and virtualbox_guest_installed_version != ""
