---
- name: Verify
  hosts: all
  gather_facts: true

  vars_files:
    - ../../defaults/main.yml
    - ../../vars/molecule.yml

  tasks:
    - name: Check installed version
      ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_version.yml"

    - name: Assert installed version is correct
      ansible.builtin.assert:
        that:
          - "virtualbox_guest_installed_version == virtualbox_guest_virtualbox_version"
