---
- name: Verify
  hosts: all
  gather_facts: true

  vars_files:
    - ../../defaults/main.yml
    - ../../vars/molecule.yml

  vars:
    ansible_user: ansible
    ansible_password: ansible
    ansible_become_password: ansible

  tasks:
    - name: Check installed version
      ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_version.yml"

    - name: Assert installed version is correct
      ansible.builtin.assert:
        that:
          - "virtualbox_guest_installed_version == virtualbox_guest_virtualbox_version"
      when: ansible_os_family not in ['FreeBSD', 'Alpine']

    - name: Assert VirtualBox Guest Additions is installed in FreeBSD and Alpine
      ansible.builtin.assert:
        that:
          - "virtualbox_guest_installed_version is defined"
          - "virtualbox_guest_installed_version != ''"
        fail_msg: "VirtualBox Guest Additions is not installed"
        success_msg: "VirtualBox Guest Additions {{ virtualbox_guest_installed_version }} is installed (package-based installation, version may differ from selected version)"
      when: ansible_os_family in ['FreeBSD', 'Alpine']
